# Root Logger
rootLogger=INFO, STDOUT, REBOOT

# Direct log messages to STDOUT
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# Direct log messages to rolling log files (new file on each reboot)
appender.reboot.type=RollingFile
appender.reboot.name=REBOOT
appender.reboot.fileName=logs/application.log
appender.reboot.filePattern=logs/application-%d{yyyy-MM-dd-HH-mm-ss}-%i.log.gz
appender.reboot.layout.type=PatternLayout
appender.reboot.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
appender.reboot.policies.type=Policies
appender.reboot.policies.startup.type=OnStartupTriggeringPolicy
appender.reboot.strategy.type=DefaultRolloverStrategy
appender.reboot.strategy.max=10
